server {
	listen 80;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	
	ssl_certificate /etc/nginx/ssl/server.crt;
	ssl_certificate_key /etc/nginx/ssl/server.key;


	location / {
		proxy_pass http://backend:5000;
		proxy_set_header Host $host;
		proxy_set_header X-Real_IP $remote_addr;
	}
}
